---
abstract: 'Handles hardware MAC Addresses (EUI-48 and EUI-64)'
author:
  - 'Dean Hamstead <dean@fragfest.com.au>'
build_requires:
  Test::Trap: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3603'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: NetAddr-MAC
provides:
  NetAddr::MAC:
    file: lib/NetAddr/MAC.pm
    version: 0.72
requires:
  Carp: 0
  List::Util: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.72
