---
abstract: 'MAC address functions and object'
author:
  - 'Dean Hamstead <dean@bytefoundry.com.au>'
build_requires:
  Test::Trap: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.020, CPAN::Meta::Converter version 2.142690'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: NetAddr-MAC
requires:
  Carp: '0'
  Exporter: '0'
  List::Util: '0'
  base: '0'
  constant: '0'
  perl: '5.004'
  strict: '0'
  vars: '0'
  warnings: '0'
version: '0.86'
