---
abstract: 'Handles hardware MAC Addresses (EUI-48 and EUI-64)'
author:
  - 'Dean Hamstead <dean@fragfest.com.au>'
build_requires:
  Test::Trap: 0
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: NetAddr-MAC
provides:
  NetAddr::MAC:
    file: lib/NetAddr/MAC.pm
    version: 0.76
requires:
  Carp: 0
  Exporter: 0
  List::Util: 0
  base: 0
  constant: 0
  perl: 5.004
  strict: 0
  vars: 0
  warnings: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.76
