---
name: NetAddr-MAC
version: v0.7.1
author:
  - 'Dean Hamstead <dean@fragfest.com.au>'
abstract: Handles hardware MAC Addresses (EUI-48 and EUI-64)
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  Test::Trap: 0
requires:
  Carp: 0
  List::Util: 0
configure_requires:
  Module::Build: 0.340201
provides:
  NetAddr::MAC:
    file: lib/NetAddr/MAC.pm
    version: v0.7.1
generated_by: Module::Build version 0.340201
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
